version: 0.0
os: linux
files:
  - source: Python
    destination: /home/ec2-user/python_deployment/Python
  - source: sample_flask_site
    destination: /home/ec2-user/python_deployment/sample_flask_site

permissions:
  - object: Python
    pattern: "s3_copy.py"
    mode: 755
    type:
      - file
  - object: scripts
    pattern: "install_packages.sh"
    mode: 755
    type:
      - file
  
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_packages.sh
      runas: root
  ValidateService:
    - location: /Python/s3_copy.py
      timeout: 120
      runas: root