version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747.zip
      - unzip sonar-scanner-cli-4.7.0.2747.zip
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747/bin/
  build:
    commands:
       - sonar-scanner -Dsonar.projectKey=ppraghu_PythonETLJobsRepo_AYMdSChx_6m7NtY5d-tG -Dsonar.sources=. -Dsonar.host.url=http://ec2-52-32-225-35.us-west-2.compute.amazonaws.com:9000
