version: 0.2

#env:
#  parameter-store:
#    SONARQUBE_TOKEN: "sqp_0120f340c986a0f9293ff328557be9c8c1df1b56"
#    SONARQUBE_ENDPOINT: "http://ec2-52-32-225-35.us-west-2.compute.amazonaws.com:9000"


phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
      - chmod 777 ./sonar-scanner-4.7.0.2747-linux/jre/bin/java
      - ./sonar-scanner-4.7.0.2747-linux/jre/bin/java -version
  #pre_build:
  #  commands:
  #    - apt-get install -y python3-venv
  build:
    commands:
       - sonar-scanner -Dsonar.projectKey=ppraghu_PythonETLJobsRepo_AYMdSChx_6m7NtY5d-tG -Dsonar.sources=. -Dsonar.host.url=http://ec2-52-32-225-35.us-west-2.compute.amazonaws.com:9000
    #  - python Python/test.py